Repository debionetwork/debio-frontend, pull requests merged in 2021-11, with the labels that each got.

#227 feat: update lab and services fields.
  src/lib/polkadotProvider/command/services.js
  src/store/substrate/types.json
  src/stories/Button.stories.js
  src/stories/Button.vue
  src/stories/Header.stories.js
  src/stories/Header.vue
  src/stories/Introduction.stories.mdx
  src/stories/Page.stories.js
  src/stories/Page.vue
  src/stories/assets/code-brackets.svg
  src/stories/assets/colors.svg
  src/stories/assets/comments.svg
  src/stories/assets/direction.svg
  src/stories/assets/flow.svg
  src/stories/assets/plugin.svg
  src/stories/assets/repo.svg
  src/stories/assets/stackalt.svg
  src/stories/button.css
  src/stories/header.css
  src/stories/page.css
  src/views/Dashboard/Lab/Account/index.vue
  src/views/Dashboard/Lab/Registration/Services/index.vue
  src/views/Dashboard/Lab/Registration/index.vue
Labels: enhancement

#226 fix: Request service flow
  src/components/HeaderUserInfo.vue
  src/store/lab/index.js
  src/views/Dashboard/Lab/RequestLab/ServiceTable/index.vue
  src/views/Dashboard/Lab/Services/Add.vue
Labels: bug

#230 add field for DNA collection process on add service lab
  src/views/Dashboard/Lab/Services/Add.vue
  src/views/Dashboard/Lab/Services/Detail.vue
Labels: enhancement

#232 ci: add github action workflow
  .github/workflows/alpha.yml
  .github/workflows/beta.yml
  .github/workflows/main.yml
  .github/workflows/mlc_config.json
  .github/workflows/publish-draft-release-candidate.yml
  .github/workflows/publish-draft-release.yml
  .github/workflows/pull-request.yml
  .github/workflows/rcb_config.json
  .github/workflows/release-candidate.yml
  .github/workflows/release.yml
  .maintain/docker/Dockerfile
Labels: ci/cd

#235 fix: lab verified status.
  src/views/Dashboard/Lab/index.vue
Labels: bug

#236 fix: notification verified.
  src/lib/polkadotProvider/events/handlers/lab.js
  src/lib/polkadotProvider/events/index.js
  src/store/substrate/event-types.json
  src/store/substrate/index.js
Labels: bug

#237 fix: show cert file.
  src/views/Dashboard/Lab/Account/Certification.vue
Labels: bug

#239 fix: lab registration stepper.
  src/views/Dashboard/Lab/Account/index.vue
  src/views/Dashboard/Lab/Registration/Services/index.vue
  src/views/Dashboard/Lab/Registration/index.vue
Labels: bug

#240 fix: No Account Shows after logout
  src/components/DialogSelectUserLogin.vue
Labels: bug

#241 fix: fixed customer care redirect to gitbook
  src/router/routes/customer.js
  src/router/routes/doctor.js
  src/router/routes/hospital.js
  src/router/routes/lab.js
Labels: enhancement

#244 ci: fixed debio-frontend deploy
  .github/workflows/alpha.yml
  .github/workflows/beta.yml
  .github/workflows/main.yml
  .github/workflows/release.yml
Labels: ci/cd

#249 ci: separate staging environment
  .github/workflows/alpha.yml
Labels: ci/cd

#250 ci: separate staging ssh
  .github/workflows/alpha.yml
Labels: ci/cd

#251 fix: bugs in edit service
  src/views/Dashboard/Lab/Services/Detail.vue
Labels: bug

#254 ci: fixed typo env
  .github/workflows/alpha.yml
Labels: ci/cd
