Repository debionetwork/debio-frontend, pull requests merged in 2021-12, with the labels that each got.

#263 ci: renamed testnet env
  .github/workflows/beta.yml
Labels: ci/cd

#280 ci: update nginx conf
  nginx/conf.d/default.conf
Labels: CI

#281 ci: improve nginx conf
  nginx/conf.d/default.conf
Labels: CI

#284 ci: update env
  .github/workflows/alpha.yml
  .github/workflows/beta.yml
  .github/workflows/main.yml
  .github/workflows/release.yml
Labels: CI

#285 Update ENV
  src/api/service-request.js
  src/components/SetKeystorePasswordDialog.vue
  src/lib/categories.js
  src/lib/location.js
  src/lib/orders.js
  src/lib/polkadotProvider/query/orders.js
  src/lib/services.js
  src/store/auth/index.js
  src/store/feedback/index.js
  src/store/lab/index.js
  src/store/registration/index.js
  src/store/wallet/index.js
Labels: enhancement

#288 fix: rules error on registration services form.
  src/views/Dashboard/Lab/Registration/Services/index.vue
Labels: bug

#286 ci: update env
  .github/workflows/alpha.yml
  .github/workflows/beta.yml
  .github/workflows/main.yml
  .github/workflows/release.yml
Labels: CI

#289 fix: removed test result in lab dashboard
  src/lib/polkadotProvider/query/orders.js
  src/views/Dashboard/Lab/OrderHistory/index.vue
  src/views/Dashboard/Lab/TestResults.vue
  src/views/Dashboard/Lab/index.vue
Labels: refactor

#292 ci: disable index.html cache
  nginx/conf.d/default.conf
Labels: CI

#293 ci: add nginx compress gzip
  .github/workflows/alpha.yml
  .github/workflows/beta.yml
  nginx/conf.d/default.conf
Labels: CI

#294 ci: add kubernetes helm charts
  .maintain/kubernetes/.helmignore
  .maintain/kubernetes/Chart.yaml
  .maintain/kubernetes/templates/_helpers.tpl
  .maintain/kubernetes/templates/deployment.yaml
  .maintain/kubernetes/templates/hpa.yaml
  .maintain/kubernetes/templates/ingress.yaml
  .maintain/kubernetes/templates/secrets.yaml
  .maintain/kubernetes/templates/service.yaml
  .maintain/kubernetes/templates/serviceaccount.yaml
  .maintain/kubernetes/templates/tests/test-connection.yaml
  .maintain/kubernetes/values.yaml
Labels: CI

#295 ci: add docker maintain scipts
  .maintain/docker/build-image.sh
  .maintain/docker/create-network.sh
  .maintain/docker/docker-compose.yml
  .maintain/docker/start-docker-compose.sh
  .maintain/docker/stop-docker-compose.sh
  nginx/conf.d/default.conf
Labels: CI

#301 ci: improve nginx conf
  .github/workflows/alpha.yml
  .github/workflows/beta.yml
  .github/workflows/main.yml
  .github/workflows/release.yml
  nginx/conf.d/default.conf
Labels: CI

#303 ci: fix digest outputs
  .github/workflows/alpha.yml
  .github/workflows/beta.yml
  .github/workflows/main.yml
  .github/workflows/release.yml
Labels: CI

#306 fix: remove balances.transfer event notification
  src/store/substrate/event-types.json
Labels: bug, enhancement

#307 ci: add new env and fix mainnet secret
  .github/workflows/alpha.yml
  .github/workflows/beta.yml
  .github/workflows/main.yml
  .github/workflows/release.yml
Labels: CI

#318 ci: use gcr private repository
  .github/workflows/alpha.yml
  .github/workflows/beta.yml
  .github/workflows/main.yml
  .github/workflows/release.yml
Labels: CI

#320 ci: enable autoscaling
  .debio.pipeline.yml
  .dockerignore
  .github/workflows/alpha.yml
  .github/workflows/beta.yml
  .github/workflows/main.yml
  .github/workflows/release.yml
  .maintain/kubernetes/.helmignore
  .maintain/kubernetes/Chart.yaml
  .maintain/kubernetes/templates/_helpers.tpl
  .maintain/kubernetes/templates/deployment.yaml
  .maintain/kubernetes/templates/hpa.yaml
  .maintain/kubernetes/templates/ingress.yaml
  .maintain/kubernetes/templates/secrets.yaml
  .maintain/kubernetes/templates/service.yaml
  .maintain/kubernetes/templates/serviceaccount.yaml
  .maintain/kubernetes/templates/tests/test-connection.yaml
  .maintain/kubernetes/values.yaml
  Dockerfile
  Dockerfile.demo
  build-demo.sh
  build-dev.sh
  build.sh
  docker-compose.yml
  release-build-dev.sh
  release.dockerfile
  reload-demo.sh
  reload-dev.sh
Labels: CI

#321 ci: improve high availability
  .github/workflows/alpha.yml
  .github/workflows/beta.yml
  .github/workflows/main.yml
  .github/workflows/release.yml
Labels: CI

#322 ci: improve build images
  .github/workflows/release.yml
Labels: CI

#323 Ci cd
  .github/workflows/release.yml
Labels: CI

#324 ci: update release deployment
  .github/workflows/release.yml
Labels: CI
