Repository debionetwork/debio-frontend, pull requests merged in 2022-10, with the labels that each got.

#530 ci: improvements
  .github/CODEOWNERS
  .github/PULL_REQUEST_TEMPLATE.md
  .github/dependabot.yaml
  .github/pull_request_template.md
  .github/workflows/analyzer.yaml
  .github/workflows/builder.yaml
  .github/workflows/cicd.yaml
  .github/workflows/cii.yaml
  .github/workflows/deployer.yaml
  .github/workflows/mlc_config.json
  .github/workflows/rcb_config.json
  .github/workflows/releaser.yaml
  .github/workflows/sast.yaml
  .github/workflows/tester.yaml
  .maintain/docker/Dockerfile
  .maintain/docker/entrypoint.sh
  .maintain/install-hooks.sh
  CODEOWNERS
  README.md
  package.json
Labels: ci

#523 feat: enhance provide service when claim request and handle balance format
  src/components/Dialog/DialogStake.vue
  src/components/DialogSelectUserLogin.vue
  src/components/HeaderWallet.vue
  src/lib/balance-format.js
  src/lib/polkadotProvider/command/services.js
  src/views/Dashboard/Lab/Registration/Services/index.vue
  src/views/Dashboard/Lab/RequestLab/ServiceTable/index.vue
  src/views/Dashboard/Lab/Services/Add.vue
  src/views/Dashboard/Lab/Services/Detail.vue
  src/views/Dashboard/Lab/Services/index.vue
Labels: feature

#557 feat: remove-metamask
  src/App.vue
  src/components/Dialog/SwitchNetwork.vue
  src/components/HeaderWallet.vue
  src/components/InstallMetamask.vue
  src/components/OrderList.vue
  src/components/WalletBinding.vue
  src/lib/api/conversion.js
  src/lib/metamask/index.js
  src/lib/metamask/mixins/README.md
  src/lib/metamask/usdt/abi.json
  src/lib/metamask/usdt/index.js
  src/lib/metamask/wallet.js
  src/lib/send-transaction.js
  src/lib/serviceHandler.js
  src/main.js
  src/store/index.js
  src/store/metamask/contracts/abi/ERC20Interface.json
  src/store/metamask/contracts/index.js
  src/store/metamask/index.js
  src/store/wallet/index.js
  src/views/Dashboard/Doctor/NavigationLayout.vue
  src/views/Dashboard/Doctor/Registration/index.vue
  src/views/Dashboard/Hospital/NavigationLayout.vue
  src/views/Dashboard/Hospital/Registration/index.vue
  src/views/Dashboard/Lab/Account/index.vue
  src/views/Dashboard/Lab/NavigationLayout.vue
  src/views/Dashboard/Lab/Registration/Services/index.vue
  src/views/Dashboard/Lab/Registration/index.vue
  src/views/Dashboard/Lab/Services/Add.vue
  src/views/Dashboard/Lab/Services/Detail.vue
  src/views/Dashboard/Lab/index.vue
Labels: feature

#560 fix: balance on wallet
  src/lib/notification.js
  src/store/substrate/index.js
Labels: fix

#564 feat: add usn and usdt to wallet
  src/assets/debio-logo.svg
  src/assets/near-logo.svg
  src/assets/tether-logo.svg
  src/components/HeaderWallet.vue
  src/lib/polkadotProvider/query/octopus-assets.js
  src/store/substrate/index.js
Labels: feature

#566 fix: wallet usn usdt
  src/components/HeaderNotification.vue
  src/components/HeaderWallet.vue
  src/lib/polkadotProvider/query/balance.js
  src/store/substrate/index.js
Labels: fix
