Repository debionetwork/debio-frontend, pull requests merged in 2022-05, with the labels that each got.

#413 fix: enhance flow staking lab
  src/router/routes/lab.js
  src/views/Dashboard/Lab/NavigationLayout.vue
  src/views/Dashboard/Lab/index.vue
Labels: fix

#419 fix: watch wallet balance
  src/components/HeaderWallet.vue
  src/store/substrate/index.js
Labels: fix

#420 fix: convert minimum staking amount
  src/components/Dialog/DialogStake.vue
Labels: fix

#422 Fix : redirect stake dialog
  src/views/Dashboard/Lab/Registration/Services/index.vue
Labels: fix

#423 fix : Staking lab
  src/router/routes/lab.js
  src/views/Dashboard/Lab/NavigationLayout.vue
  src/views/Dashboard/Lab/Registration/Services/index.vue
  src/views/Dashboard/Lab/index.vue
Labels: fix

#424 fix: flow after staking success
  src/router/routes/lab.js
  src/views/Dashboard/Lab/NavigationLayout.vue
  src/views/Dashboard/Lab/Registration/Services/index.vue
  src/views/Dashboard/Lab/index.vue
Labels: fix

#412 fix: Disabled Delete certification
  src/views/Dashboard/Lab/Account/Certification.vue
Labels: fix

#414 fix: Add validation result upload
  src/views/Dashboard/Lab/OrderHistory/ProcessOrder/ProcessSpecimen/FileCard.vue
  src/views/Dashboard/Lab/OrderHistory/ProcessOrder/ProcessSpecimen/index.vue
Labels: fix

#415 feat : Certificate is mandatory when registration
  src/views/Dashboard/Lab/Registration/index.vue
Labels: feature, improvement

#417 fix: disable fields when loading
  src/views/Dashboard/Lab/Account/Certification.vue
  src/views/Dashboard/Lab/Account/index.vue
  src/views/Dashboard/Lab/Registration/Certification.vue
  src/views/Dashboard/Lab/Registration/Services/index.vue
  src/views/Dashboard/Lab/Registration/index.vue
  src/views/Dashboard/Lab/Services/Add.vue
  src/views/Dashboard/Lab/Services/Detail.vue
Labels: fix, improvement

#425 fix: validation on reject specimen dialog
  src/views/Dashboard/Lab/OrderHistory/ProcessOrder/QualityControlSpecimen.vue
Labels: fix

#427 fix: rules password handlers
  src/constants/error-messages.js
Labels: fix

#429 feat: Improve mnemonic verify
  src/components/MnemonicTextbox.vue
  src/components/VerifyRecoveryPhraseDialog.vue
Labels: feature, improvement

#432 fix: Remove phone limit validation
  src/views/Dashboard/Lab/Account/index.vue
  src/views/Dashboard/Lab/Registration/index.vue
Labels: fix, improvement

#428 feat: order list lab dashboard
  src/components/OrderList.vue
  src/router/routes/lab.js
  src/views/Dashboard/Lab/OrderHistory/index.vue
  src/views/Dashboard/Lab/index.vue
  tests/unit/views/Dashboard/Lab/index.spec.js
Labels: feature, test

#434 ci: add new env
  .github/workflows/builder.yml
Labels: ci
