Repository debionetwork/debio-frontend, pull requests merged in 2022-08, with the labels that each got.

#493 chore: revise env-example
  .env-example
Labels: feature

#495 feat: add clear account in local storage
  src/components/SetKeystorePasswordDialog.vue
  src/components/UserAccountMenu.vue
  src/views/Dashboard/Lab/NavigationLayout.vue
Labels: feature

#497 fix: clear account and update version 2.0.6
  package-lock.json
  package.json
  src/components/SetKeystorePasswordDialog.vue
  src/components/UserAccountMenu.vue
  src/views/Dashboard/Lab/NavigationLayout.vue
Labels: fix

#494 feat: dynamic watch URL params via notification
  src/lib/polkadotProvider/events/handlers/lab.js
  src/views/Dashboard/Lab/OrderHistory/ProcessOrder/index.vue
  src/views/Dashboard/Lab/Services/Detail.vue
Labels: improvement

#498 fix: Popup redirect
  src/router/routes/lab.js
  src/views/Dashboard/Lab/RequestLab/Mapping/MapCountry.vue
  src/views/Dashboard/Lab/Services/Add.vue
Labels: fix

#500 fix: rename header table product name to service name
  src/components/OrderList.vue
Labels: fix
