Repository debionetwork/debio-frontend, pull requests merged in 2022-07, with the labels that each got.

#463 fix: duplicat notif & update wording for regist flow notification
  src/lib/polkadotProvider/events/handlers/lab.js
  src/lib/polkadotProvider/events/index.js
  src/store/substrate/event-types.json
Labels: fix

#461 feat: Add popup insufficient balance
  src/views/Dashboard/Lab/Account/index.vue
  src/views/Dashboard/Lab/OrderHistory/ProcessOrder/ProcessSpecimen/index.vue
  src/views/Dashboard/Lab/OrderHistory/ProcessOrder/QualityControlSpecimen.vue
  src/views/Dashboard/Lab/OrderHistory/ProcessOrder/ReceiveSpecimen.vue
  src/views/Dashboard/Lab/OrderHistory/ProcessOrder/WetWorkSpecimen.vue
  src/views/Dashboard/Lab/Registration/Services/List.vue
  src/views/Dashboard/Lab/Registration/Services/index.vue
  src/views/Dashboard/Lab/Services/Add.vue
  src/views/Dashboard/Lab/Services/Detail.vue
  src/views/Dashboard/Lab/Services/index.vue
Labels: feature, improvement

#462 fix: max char limit & delete english alphabet validation
  src/views/Dashboard/Lab/Registration/Services/index.vue
  src/views/Dashboard/Lab/Services/Add.vue
Labels: fix

#460 fix: process order flow notification
  src/lib/polkadotProvider/events/handlers/lab.js
  src/store/substrate/event-types.json
Labels: fix

#464 ci: improve github workflows
  .github/workflows/builder.yml
  .github/workflows/create-tags.yml
  .github/workflows/deployer.yml
  .github/workflows/release.yml
Labels: ci

#465 ci: update version & formatting
  .github/workflows/builder.yml
  .github/workflows/create-tags.yml
  .github/workflows/deployer.yml
  .github/workflows/release.yml
  .github/workflows/update-version.yml
Labels: ci

#466 fix: long description validation
  src/views/Dashboard/Lab/Registration/Services/index.vue
  src/views/Dashboard/Lab/Services/Add.vue
Labels: fix

#470 fix: claim request service flow
  src/views/Dashboard/Lab/Services/Add.vue
  src/views/Dashboard/Lab/Services/index.vue
Labels: fix

#467 fix: Popup hide after service succeed deleted
  src/views/Dashboard/Lab/Registration/Services/List.vue
Labels: fix

#471 fix: Vuetify loading indicator
  package-lock.json
  package.json
  src/views/Dashboard/Lab/Services/Add.vue
Labels: fix

#474 ci: revert "update version & formatting"
  .github/workflows/builder.yml
  .github/workflows/create-tags.yml
  .github/workflows/deployer.yml
  .github/workflows/release.yml
  .github/workflows/update-version.yml
Labels: ci

#473 ci: revert "fix create tags & release"
  .github/workflows/create-tags.yml
  .github/workflows/release.yml
Labels: ci

#476 ci: revert "improve github workflows"
  .github/workflows/builder.yml
  .github/workflows/create-tags.yml
  .github/workflows/deployer.yml
  .github/workflows/release.yml
Labels: ci

#472 fix: update verification status notification
  src/lib/polkadotProvider/events/handlers/lab.js
Labels: fix

#478 ci: added app version
  .env-example
  .github/workflows/builder.yml
Labels: ci

#477 feat: display app version
  package.json
  src/App.vue
  src/components/NavigationDrawer.vue
Labels: feature, improvement

#480 ci: get package version
  .github/workflows/builder.yml
Labels: ci

#481 chore: bump version to 2.0.5
  package.json
Labels: feature

#482 fix: package.json
  package-lock.json
  package.json
Labels: fix

#483 fix: Update decimal validation limit
  src/views/Dashboard/Lab/Registration/Services/index.vue
  src/views/Dashboard/Lab/Services/Add.vue
Labels: fix

#484 feat: update wording order to order history
  src/components/NavigationDrawer.vue
  src/router/routes/lab.js
Labels: feature

#475 fix: process order flow notification
  src/lib/polkadotProvider/events/handlers/lab.js
  src/store/substrate/event-types.json
Labels: fix

#485 fix: limit validation edit service description
  src/views/Dashboard/Lab/Services/Detail.vue
Labels: fix

#487 fix: lab regist flow notification
  src/lib/polkadotProvider/events/handlers/lab.js
Labels: fix

#486 fix: add pop up install metamask
  src/components/InstallMetamask.vue
  src/views/Dashboard/Lab/NavigationLayout.vue
Labels: test
