Repository debionetwork/debio-frontend, pull requests merged in 2022-03, with the labels that each got.

#359 [DBIO-1560] fix: validation add service form in lab registration
  src/constants/error-messages.js
  src/constants/rules.js
  src/store/auth/index.js
  src/views/Dashboard/Lab/Registration/Services/index.vue
Labels: fix

#372 ci: optimize deployment resource request & limit
  .github/workflows/deployer.yml
Labels: ci

#374 [DBIO-2085] feat: handle general api error
  src/assets/error-cable.svg
  src/components/Dialog/DialogErrorConnection.vue
  src/lib/api/index.js
  src/views/Dashboard/Lab/NavigationLayout.vue
Labels: feature

#373 [DBIO-2050] fix: Search behavior
  src/views/Dashboard/Lab/RequestLab/ServiceTable/index.vue
Labels: fix

#376 [DBIO-2149] fix: Button details view
  src/views/Dashboard/Lab/RequestLab/Mapping/SearchBar.vue
  src/views/Dashboard/Lab/RequestLab/ServiceTable/index.vue
Labels: fix

#377 ci: add new env
  .env-example
  .github/workflows/builder.yml
Labels: ci

#363 [DBIO-1341] Chore: After Lab verified, can delete all services
  src/components/Button/index.vue
  src/views/Dashboard/Lab/Services/Add.vue
  src/views/Dashboard/Lab/Services/index.vue
Labels: feature
