Repository debionetwork/debio-frontend, pull requests merged in 2022-01, with the labels that each got.

#326 feat: mixpanel and sentry analytics.
  package-lock.json
  package.json
  src/lib/api/index.js
  src/main.js
Labels: enhancement

#332 ci: improve replicas of deployments
  .github/workflows/alpha.yml
  .github/workflows/beta.yml
  .github/workflows/main.yml
  .github/workflows/release.yml
Labels: CI

#328 [DBIO-1454] fix: remove cancel button on the input password.
  src/components/UnlockWalletDialog.vue
Labels: bug

#329 [DBIO-1090] fix: remove sorting on image column
  src/views/Dashboard/Lab/Services/index.vue
Labels: bug

#330 [DBIO-1368] fix: missing action button in service table
  src/views/Dashboard/Lab/Services/index.vue
Labels: bug

#335 [DBIO-1413] fix: wrong validation error in profile image upload
  src/views/Dashboard/Lab/Registration/index.vue
Labels: bug

#331 [DBIO-1495] fix: logic login with existing account and update localstorage naming
  src/components/DialogSelectUserLogin.vue
  src/components/HeaderUserInfo.vue
  src/components/SetKeystorePasswordDialog.vue
  src/lib/local-storage.js
  src/router/routes/lab.js
  src/store/ethereum/contracts/index.js
  src/store/substrate/index.js
Labels: bug

#333 [DBIO-1451] refactor: restructure metamask/contract.json to env
  src/lib/metamask/escrow.js
  src/lib/metamask/serviceRequest.js
  src/lib/metamask/wallet.js
  src/router/index.js
  src/router/routes/customer.js
  src/store/ethereum/contracts/contract.json
  src/store/ethereum/contracts/contract_ropsten.json
  src/store/ethereum/contracts/index.js
  src/store/metamask/contracts/abi/ERC20.json
  src/store/metamask/contracts/abi/ERC20Basic.json
  src/store/metamask/contracts/abi/Escrow.json
  src/store/metamask/contracts/abi/EscrowFactory.json
  src/store/metamask/contracts/abi/ServiceRequest.json
  src/store/metamask/contracts/abi/SimpleEscrow.json
  src/store/metamask/contracts/abi/SingleEscrow.json
  src/store/metamask/contracts/contract.json
  src/store/metamask/contracts/index.js
  src/views/Dashboard/Customer/DnaCollectionInstructions.vue
  src/views/Dashboard/Customer/Documents/DocumentResult.vue
  src/views/Dashboard/Customer/Documents/DocumentsList.vue
  src/views/Dashboard/Customer/EMR/UploadEMR.vue
  src/views/Dashboard/Customer/GenomeFiles.vue
  src/views/Dashboard/Customer/Home/OrderHistory.vue
  src/views/Dashboard/Customer/Home/TestResults.vue
  src/views/Dashboard/Customer/Home/index.vue
  src/views/Dashboard/Customer/OrderHistory.vue
  src/views/Dashboard/Customer/OrderHistoryDetail/Failed.vue
  src/views/Dashboard/Customer/OrderHistoryDetail/Refund.vue
  src/views/Dashboard/Customer/OrderHistoryDetail/index.vue
  src/views/Dashboard/Customer/RequestTest/DnaCollectionRequirements.vue
  src/views/Dashboard/Customer/RequestTest/FindLab.vue
  src/views/Dashboard/Customer/RequestTest/FindTest.vue
  src/views/Dashboard/Customer/RequestTest/SelectCategory.vue
  src/views/Dashboard/Customer/RequestTest/SelectLab.vue
  src/views/Dashboard/Customer/RequestTest/ServiceRequest.vue
  src/views/Dashboard/Customer/RequestTest/StakingDialog.vue
  src/views/Dashboard/Customer/RequestTest/index.vue
  src/views/Dashboard/Customer/RequestTestCheckout/SendPaymentDialog.vue
  src/views/Dashboard/Customer/RequestTestCheckout/index.vue
  src/views/Dashboard/Customer/RequestTestReceipt.vue
  src/views/Dashboard/Customer/TestResult/index.vue
  src/views/Dashboard/Customer/TestResult/result.vue
  src/views/Dashboard/Customer/index.vue
Labels: refactor

#334 [DBIO-1410] fix: unmatched place holder
  src/views/Dashboard/Doctor/Account/index.vue
  src/views/Dashboard/Doctor/Registration/index.vue
  src/views/Dashboard/Hospital/Registration/index.vue
  src/views/Dashboard/Lab/Registration/index.vue
Labels: bug

#337 [DBIO-1140] fix: Several issue on service page
  src/views/Dashboard/Lab/Services/Add.vue
  src/views/Dashboard/Lab/Services/Detail.vue
Labels: bug

#338 [DBIO-1451] Refactor: remove unused ethereum contracts
  src/store/ethereum/contracts/abi/Account.json
  src/store/ethereum/contracts/abi/Degenics.json
  src/store/ethereum/contracts/abi/DegenicsLog.json
  src/store/ethereum/contracts/abi/EscrowFactory.json
  src/store/ethereum/contracts/abi/EternalStorage.json
  src/store/ethereum/contracts/abi/Lab.json
  src/store/ethereum/contracts/abi/Location.json
  src/store/ethereum/contracts/abi/Specimen.json
  src/store/ethereum/contracts/abi/SpecimenTracking.json
  src/store/ethereum/contracts/index.js
  src/store/ethereum/index.js
  src/views/Dashboard/Doctor/Registration/Verification.vue
  src/views/Dashboard/Doctor/Registration/index.vue
  src/views/Dashboard/Hospital/Registration/Verification.vue
  src/views/Dashboard/Hospital/Registration/index.vue
  src/views/Dashboard/Lab/Registration/Verification.vue
  src/views/Dashboard/Lab/Registration/index.vue
  src/views/Dashboard/Lab/result.vue
Labels: refactor

#339 add new env
  .github/workflows/alpha.yml
  .github/workflows/beta.yml
  .github/workflows/main.yml
  .github/workflows/release.yml
Labels: CI

#302 [DBIO-1350] fix: lab cannot change address if status Verified
  src/views/Dashboard/Lab/Account/index.vue
Labels: bug

#342 Add new env
  .github/workflows/alpha.yml
  .github/workflows/beta.yml
  .github/workflows/main.yml
  .github/workflows/release.yml
Labels: CI

#345 [DBIO-1571] Change Escrow Address
  src/lib/api/orders.js
  src/views/Dashboard/Lab/OrderHistory/ProcessOrder/index.vue
Labels: invalid

#343 [DBIO-1560] validation for user input
  src/views/Dashboard/Lab/Account/Certification.vue
  src/views/Dashboard/Lab/OrderHistory/ProcessOrder/QualityControlSpecimen.vue
  src/views/Dashboard/Lab/Registration/Certification.vue
  src/views/Dashboard/Lab/Registration/Services/index.vue
  src/views/Dashboard/Lab/Registration/index.vue
  src/views/Dashboard/Lab/Services/Add.vue
Labels: enhancement

#346 [DBIO-1621] adjust endpoint for provide service request
  src/lib/api/services.js
Labels: bug, refactor

#350 [DBIO-1555] feat: loading screen.
  src/App.vue
  src/views/Dashboard/Lab/Services/Add.vue
  src/views/Dashboard/Lab/Services/Detail.vue
  src/views/LoadingScreen.vue
Labels: enhancement

#356 DBIO-1656 - ci/cd: using environments for deployment
  .env-example
  .github/pull_request_template.md
  .github/workflows/alpha.yml
  .github/workflows/beta.yml
  .github/workflows/builder.yml
  .github/workflows/deployer.yml
  .github/workflows/main.yml
  .github/workflows/publish-draft-release-candidate.yml
  .github/workflows/publish-draft-release.yml
  .github/workflows/rcb_config.json
  .github/workflows/release.yml
  .github/workflows/tester.yml
  README.md
Labels: CI

#357 [DBIO-1666] feat: Keep ipfs file name
  src/lib/ipfs.js
  src/views/Dashboard/Doctor/Account/Certification.vue
  src/views/Dashboard/Doctor/Registration/index.vue
  src/views/Dashboard/Hospital/Account/Certification.vue
  src/views/Dashboard/Hospital/Account/index.vue
  src/views/Dashboard/Hospital/Registration/index.vue
  src/views/Dashboard/Lab/Account/Certification.vue
  src/views/Dashboard/Lab/Account/index.vue
  src/views/Dashboard/Lab/Registration/Certification.vue
  src/views/Dashboard/Lab/Registration/Services/index.vue
  src/views/Dashboard/Lab/Registration/index.vue
  src/views/Dashboard/Lab/Services/Add.vue
  src/views/Dashboard/Lab/Services/Detail.vue
  src/web-workers/ipfs-worker/ipfsWorker.js
Labels: enhancement, refactor
