Repository debionetwork/debio-frontend, pull requests merged in 2022-02, with the labels that each got.

#361 Improve tester
  .github/workflows/tester.yml
Labels: CI

#362 [DBIO-1768] Fix: Few issues on step 1 registration
  src/views/Dashboard/Lab/Registration/index.vue
Labels: bug, enhancement

#364 [DBIO-1781] ci: add nodeSelector to deployment
  .github/workflows/deployer.yml
Labels: CI

#354 [DBIO-1652] fix: Lab account verification update status
  src/lib/polkadotProvider/events/handlers/lab.js
  src/views/Dashboard/Lab/Services/Add.vue
  src/views/Dashboard/Lab/Services/index.vue
  src/views/Dashboard/Lab/index.vue
Labels: enhancement, refactor

#358 [DBIO-1266] Chore: add dialog confirmation on delete ceretification
  src/components/DataTable/index.vue
  src/views/Dashboard/Lab/Registration/Certification.vue
Labels: enhancement

#366 [DBIO-1666] fix: Minor fix ipfs name file
  src/views/Dashboard/Lab/Account/Certification.vue
  src/views/Dashboard/Lab/Account/index.vue
Labels: bug

#365 [DBIO-1639] fix: loading & disable button submit service
  src/views/Dashboard/Lab/Services/Add.vue
Labels: bug

#367 [DBIO-1814] fix: pagination tabel detail request service
  src/lib/api/service-request.js
  src/views/Dashboard/Lab/RequestLab/ServiceTable/index.vue
  src/views/Dashboard/Lab/RequestLab/index.vue
Labels: bug

#369 add AGPL-3.0 licence
  LICENSE
Labels: document
