Repository debionetwork/debio-frontend, pull requests merged in 2022-09, with the labels that each got.

#499 feat: enhance notification
  src/App.vue
  src/components/HeaderNotification.vue
  src/lib/api/index.js
  src/lib/api/notification.js
  src/lib/notification.js
  src/lib/polkadotProvider/events/handlers/customer.js
  src/lib/polkadotProvider/events/handlers/lab.js
  src/lib/polkadotProvider/events/index.js
  src/store/substrate/event-types.js
  src/store/substrate/event-types.json
  src/store/substrate/index.js
  src/store/substrate/types.json
  src/views/Dashboard/Lab/NavigationLayout.vue
  src/views/Dashboard/Lab/Registration/Services/index.vue
Labels: feature

#501 feat: enhance lab form
  src/views/Dashboard/Lab/Account/index.vue
  src/views/Dashboard/Lab/Registration/Services/index.vue
  src/views/Dashboard/Lab/Registration/index.vue
  src/views/Dashboard/Lab/Services/Add.vue
  src/views/Dashboard/Lab/Services/Detail.vue
Labels: feature

#502 fix: set currency default value
  src/views/Dashboard/Lab/Registration/Services/index.vue
  src/views/Dashboard/Lab/Services/Add.vue
  src/views/Dashboard/Lab/Services/Detail.vue
Labels: fix, feature

#503 feat: runtime env variable
  .dockerignore
  .env-template
  .maintain/docker/Dockerfile
  .maintain/docker/entrypoint.sh
  .maintain/docker/nginx/nginx.conf
  docs/metamask-wallet-creation-steps.md
  docs/test-wallet.md
  public/index.html
  src/components/NavigationDrawer.vue
  src/components/SetKeystorePasswordDialog.vue
  src/lib/api/index.js
  src/lib/metamask/wallet.js
  src/lib/pinata-proxy.js
  src/main.js
  src/router/index.js
  src/store/auth/index.js
  src/store/metamask/contracts/index.js
  src/store/wallet/index.js
  src/utils/env.js
  src/views/Dashboard/Lab/NavigationLayout.vue
  src/views/Dashboard/index.vue
  src/views/Login/index.vue
  src/views/SelectRole/index.vue
Labels: feature

#504 fix: error linter
  src/utils/env.js
Labels: fix

#505 ci: move registry to docker hub
  .github/workflows/builder.yml
Labels: ci

#506 fix: bugs on connect
  src/store/substrate/index.js
Labels: fix

#507 ci: fix docker entrypoint sed delimiter
  .maintain/docker/entrypoint.sh
Labels: ci

#508 fix: bugs on connection
  src/store/substrate/index.js
Labels: fix

#509 fix: handle account is null
  src/lib/notification.js
  src/lib/string-format.js
  src/store/substrate/index.js
Labels: fix

#511 ci: improvement
  .github/CODEOWNERS
  .github/pull_request_template.md
  .github/workflows/analyzer.yaml
  .github/workflows/builder.yaml
  .github/workflows/builder.yml
  .github/workflows/deployer.yaml
  .github/workflows/deployer.yml
  .github/workflows/mlc_config.json
  .github/workflows/rcb_config.json
  .github/workflows/releaser.yaml
  .github/workflows/tester.yaml
  .github/workflows/tester.yml
  .maintain/docker/Dockerfile
  .maintain/docker/docker-compose.yml
  .maintain/docker/entrypoint.sh
  README.md
  package.json
Labels: ci

#512 ci: bump scorecard to v2
  .github/dependabot.yaml
  .github/pull_request_template.md
  .github/workflows/analyzer.yaml
Labels: ci

#516 ci: fix scorecard version
  .github/workflows/analyzer.yaml
Labels: ci

#517 ci: fixed release auth workflow
  .github/workflows/releaser.yaml
Labels: ci

#518 ci: fix changelog builder credentials
  .github/workflows/releaser.yaml
Labels: ci

#519 ci: fixed docker builder
  .github/pull_request_template.md
  .github/workflows/analyzer.yaml
  .github/workflows/builder.yaml
  .github/workflows/mlc_config.json
Labels: ci

#510 fix: fix set notification read
  src/components/HeaderNotification.vue
  src/lib/notification.js
Labels: fix

#520 ci: cleanup ssh tunneling
  .github/workflows/deployer.yaml
  .maintain/docker/entrypoint.sh
  README.md
Labels: ci

#521 fix: get notif from localStorage
  src/lib/notification.js
Labels: fix
