Repository debionetwork/debio-frontend, pull requests merged in 2022-06, with the labels that each got.

#437 fix: Minor update duration type
  src/components/WalletBinding.vue
  src/lib/metamask/wallet.js
  src/views/Dashboard/Lab/Services/Add.vue
Labels: fix, improvement

#441 ci: use wlif for gcr auth
  .github/workflows/builder.yml
  .github/workflows/deployer.yml
  .github/workflows/tester.yml
Labels: ci

#421 fix: Rejected reason and several issues
  src/lib/polkadotProvider/query/orders.js
  src/lib/polkadotProvider/query/services.js
  src/views/Dashboard/Lab/LabOrders.vue
  src/views/Dashboard/Lab/OrderHistory/ProcessOrder/QualityControlSpecimen.vue
  src/views/Dashboard/Lab/OrderHistory/ProcessOrder/index.vue
  src/views/Dashboard/Lab/RequestLab/Mapping/MapCountry.vue
  src/views/Dashboard/Lab/Services/Add.vue
  src/views/Dashboard/Lab/Services/index.vue
Labels: fix, improvement

#431 fix: Drawer Menu Access
  src/components/NavigationDrawer.vue
  src/router/routes/lab.js
Labels: fix, refactor

#433 fix: Update validation via route
  src/lib/pinata-proxy.js
  src/router/routes/lab.js
  src/views/Dashboard/Lab/Account/Certification.vue
  src/views/Dashboard/Lab/Account/index.vue
  src/views/Dashboard/Lab/Registration/Services/List.vue
  src/views/Dashboard/Lab/Registration/index.vue
Labels: fix

#435 feat: Add maintenance page
  package-lock.json
  package.json
  src/lib/api/index.js
  src/main.js
  src/plugins/debionetwork-ui-components.js
  src/router/routes/lab.js
  src/views/maintenancePageLayout.vue
Labels: feature, improvement

#436 fix: Stepper upload result
  src/views/Dashboard/Lab/OrderHistory/ProcessOrder/ProcessSpecimen/index.vue
  src/views/Dashboard/Lab/OrderHistory/ProcessOrder/index.vue
Labels: fix, improvement

#439 fix: Handle hidden double word
  src/components/VerifyRecoveryPhraseDialog.vue
Labels: fix

#442 fix: add vcf mime type
  src/views/Dashboard/Lab/OrderHistory/ProcessOrder/ProcessSpecimen/index.vue
Labels: fix, improvement

#444 ci: add sleuth webhook
  .github/workflows/deployer.yml
Labels: ci

#448 ci: fix create draft release
  .github/workflows/builder.yml
Labels: ci

#443 fix: sub data not show
  src/views/Dashboard/Lab/RequestLab/ServiceTable/index.vue
Labels: fix

#440 fix: enhance metamask wallet and some bugs on registration
  src/components/HeaderNotification.vue
  src/components/HeaderWallet.vue
  src/components/WalletBinding.vue
  src/lib/metamask/index.js
  src/store/substrate/index.js
  src/views/Dashboard/Lab/Registration/index.vue
  src/views/Dashboard/Lab/index.vue
Labels: fix

#445 fix: Drawer navigation active menu
  src/components/NavigationDrawer.vue
  src/views/Dashboard/Lab/Services/index.vue
Labels: fix, improvement

#447 fix: VCF mime type update
  src/views/Dashboard/Lab/OrderHistory/ProcessOrder/ProcessSpecimen/index.vue
Labels: improvement

#446 feat: Validation active order
  src/components/Button.vue
  src/components/Dialog/index.vue
  src/views/Dashboard/Lab/Account/index.vue
  src/views/Dashboard/Lab/Services/index.vue
Labels: feature, improvement

#449 fix: fetch polkadot address
  src/components/SetKeystorePasswordDialog.vue
  src/store/substrate/index.js
  src/views/Dashboard/Lab/NavigationLayout.vue
Labels: fix

#451 fix: Dropdown menu and update dropdown value
  src/lib/api/conversion.js
  src/lib/api/index.js
  src/views/Dashboard/Lab/RequestLab/Mapping/MapCountry.vue
  src/views/Dashboard/Lab/Services/Add.vue
Labels: fix, feature, improvement

#452 feat: add switch network
  src/components/Dialog/SwitchNetwork.vue
  src/components/WalletBinding.vue
  src/lib/metamask/index.js
  src/views/Dashboard/Lab/NavigationLayout.vue
  src/views/Dashboard/Lab/index.vue
Labels: fix

#453 fix: Request service country code and update pinata metadata
  src/lib/pinata-proxy.js
  src/views/Dashboard/Lab/Account/Certification.vue
  src/views/Dashboard/Lab/Account/index.vue
  src/views/Dashboard/Lab/OrderHistory/ProcessOrder/ProcessSpecimen/index.vue
  src/views/Dashboard/Lab/Registration/Certification.vue
  src/views/Dashboard/Lab/Registration/Services/index.vue
  src/views/Dashboard/Lab/Registration/index.vue
  src/views/Dashboard/Lab/RequestLab/ServiceTable/index.vue
  src/views/Dashboard/Lab/Services/Add.vue
  src/views/Dashboard/Lab/Services/Detail.vue
Labels: fix, improvement

#454 fix: Notification validation
  src/lib/polkadotProvider/events/index.js
Labels: fix

#430 fix: takeout username
  src/components/HeaderUserInfo.vue
  src/components/SetKeystorePasswordDialog.vue
  src/store/substrate/index.js
Labels: fix

#456 feat: add endpoint dna-collection-process
  src/lib/api/dna-collection-process.js
  src/lib/api/index.js
  src/views/Dashboard/Lab/Registration/Services/index.vue
  src/views/Dashboard/Lab/Services/Add.vue
  src/views/Dashboard/Lab/Services/Detail.vue
Labels: fix

#438 fix: wording submit verification submitted
  src/views/Dashboard/Lab/NavigationLayout.vue
  src/views/Dashboard/Lab/index.vue
Labels: fix

#458 fix: Popup modal error
  src/components/HeaderUserInfo.vue
  src/lib/api/index.js
  src/views/Dashboard/Lab/NavigationLayout.vue
Labels: fix, improvement

#459 fix: register lab notification
  src/lib/polkadotProvider/events/handlers/lab.js
  src/store/substrate/index.js
  src/views/Dashboard/Lab/Registration/Services/index.vue
Labels: fix
