Repository debionetwork/debio-frontend, pull requests merged in 2022-12, with the labels that each got.

#598 feat: add new env for usdt token id and some minor validation in form
  .env-template
  .maintain/docker/entrypoint.sh
  src/components/HeaderWallet.vue
  src/views/Dashboard/Lab/Services/Add.vue
  src/views/Dashboard/Lab/Services/Detail.vue
Labels: feature

#597 fix: order list rejected
  src/components/OrderList.vue
  src/views/Dashboard/Lab/LabOrders.vue
Labels: fix

#601 feat: change USDT to USDT.e and fix link rules
  src/components/HeaderWallet.vue
  src/lib/balance-format.js
  src/lib/notification.js
  src/views/Dashboard/Lab/Registration/Services/List.vue
  src/views/Dashboard/Lab/Registration/Services/index.vue
  src/views/Dashboard/Lab/Services/Add.vue
  src/views/Dashboard/Lab/Services/Detail.vue
  src/views/Dashboard/Lab/Services/index.vue
Labels: fix, feature

#606 fix: minor bugs in service form
  src/views/Dashboard/Lab/Registration/Services/List.vue
  src/views/Dashboard/Lab/Registration/Services/index.vue
  src/views/Dashboard/Lab/Services/Add.vue
  src/views/Dashboard/Lab/Services/Detail.vue
Labels: fix

#609 fix: filter order list
  src/components/OrderList.vue
Labels: fix

#591 chore(main): release 2.2.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#615 fix: typo status
  src/components/OrderList.vue
Labels: fix
