Repository debionetwork/debio-frontend, pull requests merged in 2022-11, with the labels that each got.

#568 fix: order list on dashboard
  src/components/DevMenu.vue
  src/components/NavigationDrawer.vue
  src/components/OrderList.vue
  src/router/routes/lab.js
Labels: fix

#570 feat: remove USN from lab
  src/components/HeaderWallet.vue
  src/store/substrate/index.js
  src/views/Dashboard/Lab/Registration/Services/index.vue
  src/views/Dashboard/Lab/Registration/index.vue
  src/views/Dashboard/Lab/Services/Add.vue
  src/views/Dashboard/Lab/Services/Detail.vue
Labels: feature

#571 feat: Finalize Request when staking
  src/lib/polkadotProvider/command/service-request.js
  src/lib/polkadotProvider/query/service-request.js
  src/views/Dashboard/Lab/OrderHistory/ProcessOrder/ProcessSpecimen/index.vue
Labels: feature

#572 fix: check balance in register service
  src/components/Dialog/DialogStake.vue
Labels: fix

#575 fix: usd rate for conversion from USDT to USD
  src/views/Dashboard/Lab/Services/Add.vue
Labels: fix

#573 fix: currency conversion USDT
  src/views/Dashboard/Lab/Registration/Services/List.vue
Labels: fix

#584 fix: remove unused env
  .env-template
  .maintain/docker/entrypoint.sh
  src/store/auth/index.js
Labels: fix, ci

#585 fix: error on entrypoint
  .maintain/docker/entrypoint.sh
Labels: ci

#588 improvement: filter rejected in order table
  src/components/OrderList.vue
Labels: improvement

#531 chore(main): release 2.1.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending
