Repository debionetwork/debio-frontend, pull requests merged in 2022-04, with the labels that each got.

#379 fix: update filter data show
  src/views/Dashboard/Lab/LabOrders.vue
  src/views/Dashboard/Lab/OrderHistory/index.vue
Labels: improvement

#383 fix: fix linter on debio-lab
  src/views/Dashboard/Lab/Services/index.vue
Labels: fix

#384 refactor : Update the pinata gateway link with ENV
  src/lib/pinata-proxy.js
Labels: improvement

#385 ci: add new env
  .github/workflows/builder.yml
Labels: ci

#387 tests: lab dashboard and login basic page unit tests
  jest.config.js
  package-lock.json
  src/views/Dashboard/Breadcrumbs.vue
  tests/unit/views/Dashboard/Lab/OrderHistory/ProcessOrder/ProcessSpecimen/file-card.spec.js
  tests/unit/views/Dashboard/Lab/OrderHistory/ProcessOrder/ProcessSpecimen/index.spec.js
  tests/unit/views/Dashboard/Lab/OrderHistory/ProcessOrder/index.spec.js
  tests/unit/views/Dashboard/Lab/OrderHistory/ProcessOrder/quality-control-specimen.spec.js
  tests/unit/views/Dashboard/Lab/OrderHistory/ProcessOrder/receive-specimen.spec.js
  tests/unit/views/Dashboard/Lab/OrderHistory/ProcessOrder/wetwork-specimen.spec.js
  tests/unit/views/Dashboard/Lab/OrderHistory/index.spec.js
  tests/unit/views/Dashboard/Lab/Registration/Services/index.spec.js
  tests/unit/views/Dashboard/Lab/Registration/Services/list.spec.js
  tests/unit/views/Dashboard/Lab/Registration/certification.spec.js
  tests/unit/views/Dashboard/Lab/Registration/index.spec.js
  tests/unit/views/Dashboard/Lab/Registration/stepper.spec.js
  tests/unit/views/Dashboard/Lab/Registration/verification.spec.js
  tests/unit/views/Dashboard/Lab/index.spec.js
  tests/unit/views/Dashboard/Lab/lab-orders.spec.js
  tests/unit/views/Dashboard/Tests/index.spec.js
  tests/unit/views/Dashboard/breadcrumbs.spec.js
  tests/unit/views/Dashboard/index.spec.js
  tests/unit/views/Login/about-us.spec.js
  tests/unit/views/Login/index.spec.js
  tests/unit/views/Login/landing-demo.spec.js
  tests/unit/views/SelectRole/index.spec.js
  tests/unit/views/loading-screen.spec.js
Labels: test

#388 fix: add validation on file input
  src/views/Dashboard/Lab/Registration/Services/index.vue
Labels: fix

#397 fix: validation on upload sample result
  src/views/Dashboard/Lab/Registration/Services/index.vue
Labels: fix

#394 fix: missing phonecode
  src/components/HeaderUserInfo.vue
  src/views/Dashboard/Lab/Account/index.vue
Labels: fix, improvement

#396 fix: Lost value after submit
  src/views/Dashboard/Lab/Registration/Services/index.vue
Labels: fix, improvement

#400 feat: add tx weight on lab
  src/lib/pinata-proxy.js
  src/lib/polkadotProvider/command/geneticTesting.js
  src/lib/polkadotProvider/command/labs/certifications.js
  src/lib/polkadotProvider/command/labs/index.js
  src/lib/polkadotProvider/command/orders.js
  src/lib/polkadotProvider/command/services.js
  src/store/substrate/index.js
  src/utils/debounce/general/index.js
  src/utils/debounce/index.js
  src/utils/debounce/substrate/index.js
  src/utils/index.js
  src/views/Dashboard/Lab/Account/Certification.vue
  src/views/Dashboard/Lab/Account/index.vue
  src/views/Dashboard/Lab/LabOrders.vue
  src/views/Dashboard/Lab/OrderHistory/ProcessOrder/ProcessSpecimen/index.vue
  src/views/Dashboard/Lab/OrderHistory/ProcessOrder/QualityControlSpecimen.vue
  src/views/Dashboard/Lab/OrderHistory/ProcessOrder/ReceiveSpecimen.vue
  src/views/Dashboard/Lab/OrderHistory/ProcessOrder/WetWorkSpecimen.vue
  src/views/Dashboard/Lab/Registration/Certification.vue
  src/views/Dashboard/Lab/Registration/Services/index.vue
  src/views/Dashboard/Lab/Registration/index.vue
  src/views/Dashboard/Lab/Services/Add.vue
  src/views/Dashboard/Lab/Services/Detail.vue
  src/views/Dashboard/Lab/Services/index.vue
Labels: fix

#398 feat: enhance new wallet popup
  src/assets/copy-icon.svg
  src/assets/dai-icon.svg
  src/assets/metamask-icon.svg
  src/assets/polkadot-icon.svg
  src/components/HeaderNotification.vue
  src/components/HeaderUserInfo.vue
  src/components/HeaderWallet.vue
  src/views/Dashboard/Lab/NavigationLayout.vue
Labels: feature

#406 feat: add insufficient balance pop up when register
  src/assets/alert-triangle.png
  src/components/Dialog/DialogErrorBalance.vue
  src/views/Dashboard/Lab/Account/Certification.vue
  src/views/Dashboard/Lab/Registration/Certification.vue
  src/views/Dashboard/Lab/Registration/index.vue
Labels: feature

#408 feat: Add mnemonic copy button
  src/components/SecretBackupPhraseDialog.vue
Labels: feature

#405 fix: Upload to pinata
  src/views/Dashboard/Lab/OrderHistory/ProcessOrder/ProcessSpecimen/index.vue
Labels: fix

#409 fix: Minor fix encryption
  src/views/Dashboard/Lab/OrderHistory/ProcessOrder/ProcessSpecimen/index.vue
Labels: fix

#401 fix: took a long time on edit
  src/views/Dashboard/Lab/Account/Certification.vue
  src/views/Dashboard/Lab/Account/index.vue
Labels: fix, improvement

#410 feat: stake lab
  src/components/Dialog/DialogStake.vue
  src/lib/polkadotProvider/command/labs/index.js
  src/lib/polkadotProvider/query/labs/index.js
  src/views/Dashboard/Lab/Registration/Services/index.vue
Labels: feature

#403 feat: Unstake lab
  src/components/Dialog/DialogUnstake.vue
  src/lib/polkadotProvider/command/labs/index.js
  src/store/substrate/index.js
  src/views/Dashboard/Lab/Account/index.vue
Labels: feature

#404 fix: metamask balance
  src/components/HeaderWallet.vue
  src/components/WalletBinding.vue
  src/lib/metamask/wallet.js
Labels: fix

#407 fix: fix typo
  src/components/Dialog/DialogDeleteConfirmation.vue
  src/views/Dashboard/Lab/OrderHistory/ProcessOrder/ProcessSpecimen/index.vue
  src/views/Dashboard/Lab/Registration/Services/List.vue
  src/views/Dashboard/Lab/Registration/Services/index.vue
Labels: fix

#411 fix: stake lab
  src/views/Dashboard/Lab/Registration/Services/index.vue
  src/views/Dashboard/Lab/Registration/index.vue
Labels: fix
